# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_mensaje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={},
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
