# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180319_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
