# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-20 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=440, null=True, verbose_name='Nombre')),
                ('posicion', models.SmallIntegerField(default=0, verbose_name='Posición')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=400, null=True, verbose_name='Nombre')),
                ('imagen', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Fondo Miniatura Izquierdo')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=400, null=True, verbose_name='Subcategoria')),
                ('posicion', models.SmallIntegerField(default=0, verbose_name='Posición')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Subcategoria'),
        ),
    ]
